replicaCount: 2
image:
  repository: YOUR_DOCKERHUB_USERNAME/demo-app
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: NodePort
  port: 3000
  nodePort: 30080
ingress:
  enabled: false
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
